general.import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  #"~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
  "~/.config/alacritty/rose-pine-moon.toml"
]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "Cozette", style = "Medium" }
bold = { family = "Cozette", style = "Medium" }
italic = { family = "Cozette", style = "Medium" }
bold_italic = { family = "Cozette", style = "Medium" }
size = 11.0
